name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump-version:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    environment: vscode-marketplace
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_VSCODE_REPO_ACCESS_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm ci
      - name: update docs and bump version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest tag: $latest_tag"
          new_version=$(npm version patch --message "Chore(version): %s [skip-ci]")
          echo "new tag: $new_version"
          git push origin main
          git push origin $new_version
